package com.sf.netmarket.model;

import java.util.Date;

public class UserIdentification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.identify
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.user_id
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.password
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.login_type
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private String loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.login_info
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private String loginInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.bind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private Date bindTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.unbind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private Date unbindTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_identification.binded
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    private Boolean binded;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.identify
     *
     * @return the value of user_identification.identify
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.identify
     *
     * @param identify the value for user_identification.identify
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.user_id
     *
     * @return the value of user_identification.user_id
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.user_id
     *
     * @param userId the value for user_identification.user_id
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.password
     *
     * @return the value of user_identification.password
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.password
     *
     * @param password the value for user_identification.password
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.login_type
     *
     * @return the value of user_identification.login_type
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.login_type
     *
     * @param loginType the value for user_identification.login_type
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.login_info
     *
     * @return the value of user_identification.login_info
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public String getLoginInfo() {
        return loginInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.login_info
     *
     * @param loginInfo the value for user_identification.login_info
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setLoginInfo(String loginInfo) {
        this.loginInfo = loginInfo == null ? null : loginInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.bind_time
     *
     * @return the value of user_identification.bind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.bind_time
     *
     * @param bindTime the value for user_identification.bind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.unbind_time
     *
     * @return the value of user_identification.unbind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public Date getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.unbind_time
     *
     * @param unbindTime the value for user_identification.unbind_time
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setUnbindTime(Date unbindTime) {
        this.unbindTime = unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_identification.binded
     *
     * @return the value of user_identification.binded
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public Boolean getBinded() {
        return binded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_identification.binded
     *
     * @param binded the value for user_identification.binded
     *
     * @mbg.generated Mon Jun 12 22:04:55 CST 2017
     */
    public void setBinded(Boolean binded) {
        this.binded = binded;
    }
}