package com.sf.netmarket.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sf.netmarket.model.ProductInfo;
import com.sf.netmarket.model.ProductInfoExample;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    long countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    int deleteByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Wed Jun 07 23:26:42 CST 2017
     */
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);
}